# Generated by Django 4.0.5 on 2022-06-15 14:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Profile_Picture', models.ImageField(upload_to='uploads')),
                ('Email_Address', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Room_Number', models.CharField(max_length=10)),
                ('Subjects_taught', models.CharField(max_length=250)),
            ],
        ),
    ]
