# Generated by Django 4.0.5 on 2022-06-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
